server:
    port: 9001
eureka:
    client:
        service-url:
            defaultZone: http://localhost:8761/eureka/
my:
    args:
        int: 10
        str: '测试字符串1'
spring:
    application:
        name: first-config-client-dev
